/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rent;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class rentail extends javax.swing.JFrame {
     Connection con;
                PreparedStatement pst;
                ResultSet rs;
                
                PreparedStatement pst1;
                PreparedStatement pst2;
                
                PreparedStatement pst3;
                PreparedStatement pst4;

    /**
     * Creates new form rental
     */
    public rentail() {
        initComponents();
        
        LoadCatid();
        LoadCustid();
        
        txtdate.setDateFormatString("dd/MM/yyyy");
        txtdue.setDateFormatString("dd/MM/yyyy");
        
        combocust_ID.setEnabled(false);
//        txtcustname.setEnabled(false);
//        jLabel8.setEnabled(false); //Haris++
        txtdate.setEnabled(false);
        txtdue.setEnabled(false);
        
    }
               
                
        public void LoadCatid()
        {
        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            con = DriverManager.getConnection("jdbc:mysql://localhost/oopproject","root","");
                String yes = "Yes";

                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/oopproject","root","");
            
                pst = con.prepareStatement("select car_no from carregistration Where available = '"+yes+"'");
                rs = pst.executeQuery();
                combocarID.removeAllItems();
            
                while(rs.next())
                {
                    combocarID.addItem(rs.getString(1));
                     
                }
            }catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(rentail.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        
         public void LoadCustid()
        {
        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            con = DriverManager.getConnection("jdbc:mysql://localhost/oopproject","root","");
                

                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/oopproject","root","");
            
                pst = con.prepareStatement("select cust_id from customer ");
                rs = pst.executeQuery();
                combocust_ID.removeAllItems();
            
                while(rs.next())
                {
                    combocust_ID.addItem(rs.getString(1));
                     
                }
            }catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(rentail.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combocarID = new javax.swing.JComboBox<>();
        combocust_ID = new javax.swing.JComboBox<>();
        txtrentail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtdue = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rental"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Available Car ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 110, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rental Fee (RM)/Day");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        combocarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocarIDActionPerformed(evt);
            }
        });
        combocarID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combocarIDKeyPressed(evt);
            }
        });
        jPanel1.add(combocarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 134, 31));

        combocust_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocust_IDActionPerformed(evt);
            }
        });
        jPanel1.add(combocust_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 130, 30));

        txtrentail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrentailActionPerformed(evt);
            }
        });
        jPanel1.add(txtrentail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 134, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Booking Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Return Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 80, -1));
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 134, -1));
        jPanel1.add(txtdue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 134, -1));

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 93, 49));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 89, 49));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Car Booking Form");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oooooo.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 530, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.hide();
        Menu d = new Menu();
         d.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void combocarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocarIDActionPerformed
        String car_no = combocarID.getSelectedItem().toString();
        
        try {
           

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/oopproject","root","");
            
            pst1 = con.prepareStatement("select * from carregistration where car_no= ? AND available = Yes" );
            pst1.setString(1,car_no);
            rs = pst.executeQuery();
            
            
            if(rs.next())
            {               
//                String aval = rs.getString("available");
//                txtavl.setText(aval.trim());  
//                
//                if(aval.equals("Yes"))
//                {
                    combocust_ID.setEnabled(true);
                    txtdate.setEnabled(true);
                    txtdue.setEnabled(true);
//                }
//                else if(aval.equals("No"))
//                {
//                    combocust_ID.setEnabled(false);
//                    txtdate.setEnabled(false);
//                    txtdue.setEnabled(false);
//                }
                
            }
            
            else
            {
                JOptionPane.showMessageDialog(this,"Car No Not Found");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(rentail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combocarIDActionPerformed

    
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String car_id = combocarID.getSelectedItem().toString();
        String cust_id = combocust_ID.getSelectedItem().toString();
        String fee = txtrentail.getText();
        
// 
        
        SimpleDateFormat Date_Format = new SimpleDateFormat("dd-MM-yyyy");
        String date = Date_Format.format(txtdate.getDate());
        
        SimpleDateFormat Date_Format1 = new SimpleDateFormat("dd-MM-yyyy");
        String due = Date_Format1.format(txtdue.getDate());
        
        try {
//            Class.forName("com.mysql.jdbc.Driver");
//             con = DriverManager.getConnection("jdbc:mysql://localhost/oopproject","root","");

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/oopproject","root","");
             
             pst3 = con.prepareStatement("insert into rentail (car_id,cust_id,fee,date,due) values (?,?,?,?,?)");
             pst3.setString(1, car_id);
             pst3.setString(2, cust_id);
             pst3.setString(3, fee); //Haris++
             pst3.setString(4, date);
             pst3.setString(5, due);
             pst3.executeUpdate();
             
             
             pst4 = con.prepareStatement("Update carregistration set available='No' Where car_no = ?");
             pst4.setString(1, car_id);
             pst4.executeUpdate();
             
             JOptionPane.showMessageDialog(this,"Successfully Booked!");
             

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(rentail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(rentail.class.getName()).log(Level.SEVERE, null, ex);
        }
              
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtrentailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrentailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrentailActionPerformed

    private void combocarIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combocarIDKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_combocarIDKeyPressed

    private void combocust_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocust_IDActionPerformed
             String cust_id = combocust_ID.getSelectedItem().toString();
        
        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            con = DriverManager.getConnection("jdbc:mysql://localhost/oopproject","root","");

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/oopproject","root","");
            
            pst1 = con.prepareStatement("select * from customer where cust_id = ?");
            pst1.setString(2,cust_id);
            rs = pst.executeQuery();
            
            
             if(rs.next())
            {               
//                String aval = rs.getString("available");
//                txtavl.setText(aval.trim());  
//                
//                if(aval.equals("Yes"))
//                {
                    combocarID.setEnabled(true);
                    txtdate.setEnabled(true);
                    txtdue.setEnabled(true);
//                }
//                else if(aval.equals("No"))
//                {
//                    combocust_ID.setEnabled(false);
//                    txtdate.setEnabled(false);
//                    txtdue.setEnabled(false);
//                }
//                
            }
            else
            {
                 JOptionPane.showMessageDialog(this,"Cust  Not Found");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(rentail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combocust_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rentail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rentail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rentail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rentail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rentail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combocarID;
    private javax.swing.JComboBox<String> combocust_ID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser txtdate;
    private com.toedter.calendar.JDateChooser txtdue;
    private javax.swing.JTextField txtrentail;
    // End of variables declaration//GEN-END:variables
}
